create table branches (
    id int primary key generated by default as identity,
    branch_name varchar(5)
);

create table roles (
    id int primary key generated by default as identity,
    name varchar(50)
);

create table users(
    id int primary key generated by default as identity,
    username varchar(200),
    email varchar(200),
    phone_number varchar(11),
    address varchar(200),
    password varchar(100),
    status varchar(10),
    user_role int not null,
    user_branch int not null,
    foreign key(user_role) references roles(id),
    foreign key(user_branch) references branches(id)
);

create table opentalks(
    id int primary key generated by default as identity,
    topic varchar(100),
    date timestamp,
    link varchar(1000),
    opentalk_branch int not null,
    foreign key(opentalk_branch) references branches(id)
);

create table user_opentalk_details(
    user_id int not null,
    opentalk_id int not null,
    foreign key (user_id) references users(id),
    foreign key(opentalk_id) references opentalks(id)
);

create table staffs(
    id int primary key generated by default as identity,
    firstname varchar(100),
    lastname varchar(100),
    email varchar(200),
    password varchar(500)
);

create table mails(
    id int primary key generated by default as identity,
    mail_title varchar(100),
    message_content varchar(2000),
    date timestamp,
    sender_id int not null,
    foreign key (sender_id) references users(id)
);

create table user_mail_details(
    receiver_id int not null,
    mail_id int not null,
    foreign key (receiver_id) references users(id),
    foreign key (mail_id) references mails(id)
)